"""
Django settings for cvbuilder_backend project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-t+6$xv8_1(z^^)b6&01jx7d29--mr#rh39pn=%y)mfx$d6ral0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# For API, disable automatic slash appending to avoid issues with DRF custom actions
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    'storages',  # Django storages for GCS

    # Local apps
    'users',
    'resumes',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cvbuilder_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cvbuilder_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'cvbuilder'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'cvbuilder_backend.authentication.SupabaseAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 9,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# Supabase Configuration
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY')
SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET')

# Frontend URL
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
]
CORS_ALLOW_CREDENTIALS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    FRONTEND_URL,
]

# Stripe Settings
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
STRIPE_SINGLE_CV_PRICE_ID = os.getenv('STRIPE_SINGLE_CV_PRICE_ID')
STRIPE_SUBSCRIPTION_MONTHLY_PRICE_ID = os.getenv('STRIPE_SUBSCRIPTION_MONTHLY_PRICE_ID')
STRIPE_SUBSCRIPTION_YEARLY_PRICE_ID = os.getenv('STRIPE_SUBSCRIPTION_YEARLY_PRICE_ID')

# OAuth Settings (now handled by Supabase)
# Configure OAuth providers in your Supabase dashboard

# Static Files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Google Cloud Storage Settings
USE_GCS = os.getenv('USE_GCS', 'False') == 'True'

# GCS Configuration (common settings)
GS_BUCKET_NAME = os.getenv('GCS_BUCKET_NAME', 'cvbuilder-images')
GS_PROJECT_ID = os.getenv('GCS_PROJECT_ID', 'cvbuilder-476609')

# GCS Credentials handling
# Supports both file path (local dev) and JSON string (Docker/production)
import json
import tempfile

credentials_path = os.getenv('GCS_CREDENTIALS_PATH')
credentials_json = os.getenv('GCS_CREDENTIALS_JSON')

if credentials_json:
    # For Docker Swarm/secrets: create a temporary file with the JSON credentials
    try:
        credentials_data = json.loads(credentials_json)
        # Create a temporary file that will persist for the application lifetime
        temp_creds_file = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.json')
        json.dump(credentials_data, temp_creds_file)
        temp_creds_file.close()
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = temp_creds_file.name
    except json.JSONDecodeError as e:
        import logging
        logging.error(f"Failed to parse GCS_CREDENTIALS_JSON: {e}")
elif credentials_path:
    # For local development: use file path directly
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credentials_path

if USE_GCS:
    # Django 5.1+ STORAGES setting for GCS
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

    # GCS specific settings
    GS_DEFAULT_ACL = 'publicRead'  # Make uploaded files publicly accessible
    GS_FILE_OVERWRITE = True  # Allow overwriting files with the same name
    GS_MAX_MEMORY_SIZE = 5242880  # 5MB - files larger than this will be streamed

    # Media files will be served from GCS
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
else:
    # Local storage for development
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Celery Settings
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Stripe Configuration
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Stripe Price IDs (must be created in Stripe Dashboard)
# Single CV purchase (one-time payment of 2.40€)
STRIPE_SINGLE_CV_PRICE_ID = os.environ.get('STRIPE_SINGLE_CV_PRICE_ID', '')

# Lifetime premium access (one-time payment of 24€)
STRIPE_LIFETIME_PREMIUM_PRICE_ID = os.environ.get('STRIPE_LIFETIME_PREMIUM_PRICE_ID', '')

# Payment amounts (in cents)
PAYMENT_AMOUNT_PAY_PER_CV = 240  # 2.40€
PAYMENT_AMOUNT_LIFETIME_PREMIUM = 2400  # 24€

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'resumes': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
