# Generated by Django 5.1 on 2025-10-29 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                help_text="Related resume for single CV purchase",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="resumes.resume",
            ),
        ),
    ]
