# Generated by Django 5.1 on 2025-10-29 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resumes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="resumes.resume",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="resumes.resume",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="resumes.resume",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resumes",
                to="resumes.template",
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["session_id"], name="resumes_session_844269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(fields=["user"], name="resumes_user_id_23a48f_idx"),
        ),
    ]
