# Generated by Django 4.2.25 on 2025-10-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_resume_email_alter_resume_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resumes.template'),
        ),
    ]
