# Generated by Django 4.2.25 on 2025-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='driving_license',
            field=models.CharField(blank=True, help_text='Driving license type', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality', max_length=100),
        ),
    ]
