# Generated by Django 4.2.25 on 2025-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_date_of_birth_resume_driving_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code', max_length=20),
        ),
    ]
