# Generated by Django 4.2.25 on 2025-10-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_city_resume_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], help_text='Education mode (remote, onsite, hybrid)', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], help_text='Work mode (remote, onsite, hybrid)', max_length=20),
        ),
    ]
