# Generated by Django 4.2.25 on 2025-11-02 11:31

from django.db import migrations, models
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_recreate_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=resumes.models.resume_photo_upload_path),
        ),
    ]
