# Generated by Django 4.2.16 on 2025-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0012_alter_resume_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("business", "Business"),
                    ("creative", "Creative"),
                    ("education", "Education"),
                    ("medical", "Medical"),
                    ("legal", "Legal"),
                    ("sales", "Sales & Marketing"),
                    ("hospitality", "Hospitality"),
                    ("engineering", "Engineering"),
                    ("minimalist", "Minimalist"),
                    ("sidebar", "Sidebar"),
                    ("startup", "Startup"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Template category for filtering",
                max_length=50,
            ),
        ),
    ]
