# Generated by Django 4.2.16 on 2025-11-03 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0013_template_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("business", "Business"),
                            ("creative", "Creative"),
                            ("education", "Education"),
                            ("medical", "Medical"),
                            ("legal", "Legal"),
                            ("sales", "Sales & Marketing"),
                            ("hospitality", "Hospitality"),
                            ("engineering", "Engineering"),
                            ("minimalist", "Minimalist"),
                            ("sidebar", "Sidebar"),
                            ("startup", "Startup"),
                            ("other", "Other"),
                        ],
                        help_text="Unique identifier for the category",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the category", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the category"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Template Categories",
                "db_table": "template_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="template",
            name="category",
        ),
        migrations.AddField(
            model_name="template",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Template categories for filtering (can have multiple)",
                related_name="templates",
                to="resumes.templatecategory",
            ),
        ),
    ]
