# Generated by Django 4.2.16 on 2025-11-03 13:02

from django.db import migrations


def populate_categories(apps, schema_editor):
    """Create all the template categories"""
    TemplateCategory = apps.get_model('resumes', 'TemplateCategory')

    categories = [
        {'slug': 'tech', 'name': 'Technology', 'description': 'Templates for technology and IT professionals', 'order': 1},
        {'slug': 'business', 'name': 'Business', 'description': 'Templates for business professionals', 'order': 2},
        {'slug': 'creative', 'name': 'Creative', 'description': 'Templates for creative professionals', 'order': 3},
        {'slug': 'education', 'name': 'Education', 'description': 'Templates for educators and academics', 'order': 4},
        {'slug': 'medical', 'name': 'Medical', 'description': 'Templates for healthcare professionals', 'order': 5},
        {'slug': 'legal', 'name': 'Legal', 'description': 'Templates for legal professionals', 'order': 6},
        {'slug': 'sales', 'name': 'Sales & Marketing', 'description': 'Templates for sales and marketing professionals', 'order': 7},
        {'slug': 'hospitality', 'name': 'Hospitality', 'description': 'Templates for hospitality industry', 'order': 8},
        {'slug': 'engineering', 'name': 'Engineering', 'description': 'Templates for engineers', 'order': 9},
        {'slug': 'minimalist', 'name': 'Minimalist', 'description': 'Clean and minimalist templates', 'order': 10},
        {'slug': 'sidebar', 'name': 'Sidebar', 'description': 'Templates with sidebar layout', 'order': 11},
        {'slug': 'startup', 'name': 'Startup', 'description': 'Templates for startup professionals', 'order': 12},
        {'slug': 'other', 'name': 'Other', 'description': 'Other template categories', 'order': 13},
    ]

    for cat_data in categories:
        TemplateCategory.objects.get_or_create(
            slug=cat_data['slug'],
            defaults={
                'name': cat_data['name'],
                'description': cat_data['description'],
                'order': cat_data['order']
            }
        )


def reverse_populate_categories(apps, schema_editor):
    """Remove all categories"""
    TemplateCategory = apps.get_model('resumes', 'TemplateCategory')
    TemplateCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0014_templatecategory_remove_template_category_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate_categories),
    ]
