# Generated by Django 5.1 on 2025-10-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("lifetime", "Lifetime"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
