# Generated by Django 4.2.25 on 2025-11-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_default_uuid_to_allauth_tables'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
